print("sa dude!!")
print("You're sleeping. Fucking Payne(fuckin noobard) comes into your room.")
print("Be careful, he's horny.")
print("Oh fuck!!")
print("He's damn horny. He even tried to lick his own dick before comong to you")
print("yup that's the level of horny he is....I feel really sorry for you")
print("He starts licking the hair on your legs to your asshole and now...")
print("He's gonna fuck you really hard, like even harder than a diamond")
print("you won't even be able to sit or shit anymore")
print("He's just pulled out his dick from his pants..wait.....\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
print("That's really small(can't even call that a dick...I mean it's really not a dick...you know what I mean it's just too small)")
print("Like even the NASA scientists couldn't see it with their holy shit huge telescopes and electronic microscopes.")
print("like even smaller than this dot () see you can't even see this dot.")
print("Anyways what would you do??let him fuck you or run or hide?")
option = int(input("Enter your answer, would you run: 1 , hide: 2, let him fuck you: 3\n type your answer here: "))
if option == 1:
    print("You can't run from this, he IS GONNA FUCK you!!!!!!Bad luck, Game Over. It's alright maybe next time you'll win")
if option == 2:
    print("You can hide anywhere you want but he's gonna  lick you all over and then fuckin rape you!!!")
else: print("\nReally would you really let him fuck you, you're such a pity little bastard you fuckin stinky ass bitch with cum of a fuckin 150 year old Morgan Freeman")    